### ISSUE TITLE
The initial loader of the website is bad. Please improve. 

### ISSUE THREAD

**Issue by ArfatSalman** [pesto-students/little-tags-deepakbhadoriya-HimatejaMerlapaka-frontend#31]
![Screenshot 2021-03-07 at 6 17 54 PM](https://user-images.githubusercontent.com/10287217/110240349-8091c180-7f71-11eb-8617-19e14a5b204c.png)

It just says `Loading...`. Do something better. On slower connections, this screen stays on the screen for 3-4 seconds. You do not want your users to see this.

**Comment by iamhimateja** [comment]
Resolved in this update https://github.com/pesto-students/little-tags-deepakbhadoriya-HimatejaMerlapaka-frontend/pull/39
